/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-02-02 06:23:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import esVo.ChatListVo;
import esVo.UserInfoVo;
import esDao.LoginDao;
import esVo.EmojiVo;
import esDao.MessageDao;
import esVo.LanguageVo;
import java.util.ArrayList;
import esDao.LanguageDao;

public final class message_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("esDao.LoginDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("esDao.MessageDao");
    _jspx_imports_classes.add("esVo.EmojiVo");
    _jspx_imports_classes.add("esVo.ChatListVo");
    _jspx_imports_classes.add("esVo.LanguageVo");
    _jspx_imports_classes.add("esVo.UserInfoVo");
    _jspx_imports_classes.add("esDao.LanguageDao");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LoginDao LoginDao = new LoginDao();
	LanguageDao langDao = new LanguageDao();
	ArrayList<LanguageVo> listLanguageVo = langDao.getLanguage();
	int userIdx = 0;
	UserInfoVo userList = null;
	int howManyAlarm = 0;
	try{
		userIdx = (Integer)request.getSession().getAttribute("userIdx"); //--> 로그인창 만들면 이걸로 적용하기	
		userList = LoginDao.getUserInfoBy(userIdx);
		howManyAlarm = (Integer)LoginDao.getCountAlarm(userIdx);
	} catch (NullPointerException e){
		e.printStackTrace();
	}
	MessageDao messDao = new MessageDao();
	ArrayList<EmojiVo> listEmojiVo = (ArrayList<EmojiVo>)(request.getAttribute("listEmojiVo")); 
	ArrayList<ChatListVo> chatList = (ArrayList<ChatListVo>)(request.getAttribute("chatList"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>메시지 - 에어비앤비</title>\r\n");
      out.write("		<link rel=\"shortcut icon\" href=\"images/logo2.png\">\r\n");
      out.write("		<link rel =\"stylesheet\" href=\"css/message.css\"/>\r\n");
      out.write("		<script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("		<script src=\"js/message.js\"></script>\r\n");
      out.write("		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body id=\"body\">\r\n");
      out.write("		<div class=\"currency_language_background\"></div>\r\n");
      out.write("				<div id=\"currency_language_\">\r\n");
      out.write("					<button class=\"close_div\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;\"><path d=\"m6 6 20 20M26 6 6 26\"></path></svg></button>\r\n");
      out.write("					<div id=\"currency_\">\r\n");
      out.write("						<div id=\"currency_top\">\r\n");
      out.write("							<button class=\"currency_button fl\">언어와 지역</button>\r\n");
      out.write("							<button class=\"language_button fl\">통화</button>\r\n");
      out.write("						</div><!--currency_top-->\r\n");
      out.write("						<div id=\"currency_center\">\r\n");
      out.write("							<div>\r\n");
      out.write("                         <h2>추천 언어 및 지역</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"fl\">\r\n");
      out.write("                              <div>한국어</div>\r\n");
      out.write("                              <div>대한민국</div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li class=\"fl\">\r\n");
      out.write("                              <div>English</div>\r\n");
      out.write("                              <div>United States</div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div>\r\n");
      out.write("                        <h3 style=\"font-size: 22px; font-weight: 600;\">언어와 지역을 선택하세요</h3>\r\n");
      out.write("                         ");

                        	for( int i = 0; i <= 90; i++ ){
  								if(i % 5 == 0)
  									out.println("<ul>");
                        
      out.write("\r\n");
      out.write("                           <li class=\"fl\">\r\n");
      out.write("                              <div>");
      out.print(listLanguageVo.get(i).getLanguage() );
      out.write("</div>\r\n");
      out.write("                              <div>");
      out.print(listLanguageVo.get(i).getLocation() );
      out.write("</div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        ");

                        	if(i % 5 == 4)
                        			out.println("</ul>");
                        	}
                        
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("						</div><!--currency_center-->\r\n");
      out.write("					</div><!--currency_-->\r\n");
      out.write("					<div id=\"language_\"></div><!--language_-->\r\n");
      out.write("				</div><!--currency_language_-->\r\n");
      out.write("		<div id=\"header\">\r\n");
      out.write("			<div id=\"header_left\" class=\"fl\">\r\n");
      out.write("				<a href=\"Main2\"><img src=\"images/logo.png\" class=\"fr\"/></a>\r\n");
      out.write("			</div><!--header_left-- <!--airbnbë¡ê³ -->\r\n");
      out.write("			<div id=\"header_center\" class=\"fl\">\r\n");
      out.write("			</div><!--header_center--> \r\n");
      out.write("			<div id=\"header_right\" class=\"fl\">\r\n");
      out.write("				<div id=\"areaair\" class=\"fl\">\r\n");
      out.write("					<a href=\"doairbnb.html\"><strong>당신의 공간을 에어비앤비하세요</strong></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"globe\" class=\"fl\">\r\n");
      out.write("					<img src=\"images/globe.png\"/>\r\n");
      out.write("				</div><!--globe-->\r\n");
      out.write("				<div id=\"profile\" class=\"fl\">\r\n");
      out.write("					<img src=\"images/list.png\" style=\"margin: 21px 0 0 0px;\"/>\r\n");
      out.write("					");
 		if(userIdx == 0) { 
      out.write("\r\n");
      out.write("								<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 30px; width: 40px; fill: currentcolor; margin: -30px 0 0 41px;\"><path d=\"M16 .7C7.56.7.7 7.56.7 16S7.56 31.3 16 31.3 31.3 24.44 31.3 16 24.44.7 16 .7zm0 28c-4.02 0-7.6-1.88-9.93-4.81a12.43 12.43 0 0 1 6.45-4.4A6.5 6.5 0 0 1 9.5 14a6.5 6.5 0 0 1 13 0 6.51 6.51 0 0 1-3.02 5.5 12.42 12.42 0 0 1 6.45 4.4A12.67 12.67 0 0 1 16 28.7z\"></path></svg>\r\n");
      out.write("						");
  } else { 
      out.write("\r\n");
      out.write("								");
 if(userList.getUser_image() != null) { 
      out.write("\r\n");
      out.write("								<img src=\"");
      out.print(userList.getUser_image() );
      out.write("\"/>\r\n");
      out.write("								");
 } else { 
      out.write("\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 30px; width: 40px; fill: currentcolor; margin: -30px 0 0 41px;\"><path d=\"M16 .7C7.56.7.7 7.56.7 16S7.56 31.3 16 31.3 31.3 24.44 31.3 16 24.44.7 16 .7zm0 28c-4.02 0-7.6-1.88-9.93-4.81a12.43 12.43 0 0 1 6.45-4.4A6.5 6.5 0 0 1 9.5 14a6.5 6.5 0 0 1 13 0 6.51 6.51 0 0 1-3.02 5.5 12.42 12.42 0 0 1 6.45 4.4A12.67 12.67 0 0 1 16 28.7z\"></path></svg>\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("								<div id=\"notice\">");
      out.print(howManyAlarm );
      out.write("</div>\r\n");
      out.write("						");
    } 
      out.write("\r\n");
      out.write("				</div><!--profile-->\r\n");
      out.write("				<div style =\"clear : both;\"></div>\r\n");
      out.write("				<div class=\"profile_list\">\r\n");
      out.write("					");
 if(userIdx > 0) { 
      out.write(" \r\n");
      out.write("					<div class=\"profile_list_top\">\r\n");
      out.write("						<form action=\"SesController\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"메시지\"/>\r\n");
      out.write("							<input type=\"hidden\" name=\"thisUserIdx\" value=\"0\"/>\r\n");
      out.write("							<input type=\"hidden\" name=\"command\" value=\"message\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"notification.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"알림\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"trip.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"여행\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"wishlist.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"위시리스트\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div><!--profile_list_top-->\r\n");
      out.write("					<div class=\"profile_list_center\">\r\n");
      out.write("						<form action=\"doairbnb.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"당신의 공간을 에어비앤비하세요\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"account.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"계정\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div><!--profile_list_center-->\r\n");
      out.write("					<div class=\"profile_list_bottom\">\r\n");
      out.write("						<form action=\"timeline.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"타임라인\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<div class=\"Logout\">로그아웃</div>\r\n");
      out.write("					</div><!--profile_list_bottom-->\r\n");
      out.write("				 	");
 } else{ 
      out.write("\r\n");
      out.write("					<div class=\"profile_list_diff\">\r\n");
      out.write("						<div>로그인</div>\r\n");
      out.write("						<div>회원가입</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</div><!--profile_list-->\r\n");
      out.write("			</div><!--header_right-->\r\n");
      out.write("			<div style =\"clear : both;\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("			<!-- 회원가입창 -->\r\n");
      out.write("   <div id=\"joinmember_outer\"></div>\r\n");
      out.write("      <div id=\"joinmember\">\r\n");
      out.write("      \r\n");
      out.write("         <div class=\"jm_header\">\r\n");
      out.write("            <button>\r\n");
      out.write("               <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"\r\n");
      out.write("                  aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"\r\n");
      out.write("                  style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: 0 auto;\">\r\n");
      out.write("                  <path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("            <h2>로그인 또는 회원 가입</h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"jm_section\">\r\n");
      out.write("            <h2>에어비엔비에 오신것을 환영합니다</h2>\r\n");
      out.write("         \r\n");
      out.write("            <form id=\"jm_form\" action=\"SesController\" method=\"post\">\r\n");
      out.write("               <div>\r\n");
      out.write("                  <label for=\"jm_form\" id=\"code\"></label> \r\n");
      out.write("                  <select name=\"jm_code\" class=\"jm_seclect_box\">\r\n");
      out.write("                     <option value=\"korean\">선호하는 언어</option>\r\n");
      out.write("                     ");
 for(int i = 0; i <= 90; i++) { 
      out.write("\r\n");
      out.write("                  	 		<option>");
      out.print(listLanguageVo.get(i).getLocation() );
      out.write("</option>\r\n");
      out.write("                  	 ");
 } 
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("	               </div>\r\n");
      out.write("	               \r\n");
      out.write("	               <input type=\"text\" class=\"jm_phnum\" placeholder=\"전화번호\" name=\"phone_num\" required/>\r\n");
      out.write("	           	   <input type=\"password\" class=\"password\" placeholder=\"비밀번호\" name=\"pw\" required/>\r\n");
      out.write("	               <span>전화나 문자로 전화번호를 확인하겠습니다. 일반 문자 메시지 요금 및 데이터 요금이 부과됩니다.</span>\r\n");
      out.write("	         	   <input type=\"hidden\" name=\"url\" value=\"message.jsp\"/>\r\n");
      out.write("	         	   <input type=\"hidden\" name=\"command\" value=\"login\"/>\r\n");
      out.write("	               <input type=\"submit\" class=\"jm_submit\" value=\"로그인\"><br/>\r\n");
      out.write("               <div class=\"join_user\" style=\"padding-top: 16px;\">회원 가입</div>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"join_user\">\r\n");
      out.write("      		<button>\r\n");
      out.write("               <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"\r\n");
      out.write("                  aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"\r\n");
      out.write("                  style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: 0 auto;\">\r\n");
      out.write("                  <path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("      		<form method=\"post\" class=\"join_user_form\" action=\"SesController\">\r\n");
      out.write("      			이름 : <input type=\"text\" placeholder=\"Ex) 김철수\" name=\"user_id\" required/> <br/><br/><br/>\r\n");
      out.write("      			비밀번호 : <input type=\"password\" name=\"pw\" required/> <br/><br/><br/>\r\n");
      out.write("      			비밀번호 확인 : <input type=\"password\" class=\"check_pw\" required/> <br/><br/><br/>\r\n");
      out.write("      			휴대폰 번호 : <input type=\"number\" name=\"phone_num\" placeholder=\"010xxxx1234\" required/> <br/><br/><br/>\r\n");
      out.write("      			거주지 : <input type=\"text\" name=\"user_regidence\" required/> <br/><br/><br/>\r\n");
      out.write("      			생년월일 : <input type=\"text\" name=\"birthday\" placeholder=\"2000/12/12\"required/> <br/><br/><br/>\r\n");
      out.write("      			이메일 : <input type=\"email\" name=\"email\" placeholder=\"asd123@naver.com\" required/> <br/><br/><br/><br/>\r\n");
      out.write("      			<input type=\"hidden\" name=\"command\" value=\"join\"/>\r\n");
      out.write("      			<input type=\"submit\" style=\"width: 500px; background-color: rgb(255,56,92); border-radius: 10px; color: white; border: none;}\"/>\r\n");
      out.write("      		</form>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--회원가입창 끝  -->\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("		");
 if(userIdx > 0) { 
      out.write("\r\n");
      out.write("			<div id=\"chatting_list\" class=\"fl\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<div class=\"fl\" id=\"mess\">\r\n");
      out.write("						<h1>메시지</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"fl\" id=\"mess_svg\">\r\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 16px; width: 16px; fill: var(--f-k-smk-x);\"><path d=\"M14 25h4v4h-4zm-4-3h12v-4H10zm-4-7h20v-4H6zM2 4v4h28V4z\"></path></svg>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"message_filter\">\r\n");
      out.write("						<div>모든 메시지</div>\r\n");
      out.write("						<div>보관 처리한 메시지(0)</div>\r\n");
      out.write("						<div>읽지 않은 메시지(0)</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<div>\r\n");
      out.write("						");
 for(ChatListVo vo : chatList) { 
      out.write("\r\n");
      out.write("							<div class=\"chat_list\"><a>\r\n");
      out.write("								<div class=\"pro_img fl\"><img src=\"");
      out.print(vo.getUserImage());
      out.write("\"/></div>\r\n");
      out.write("								<div class=\"other_name fl\">");
      out.print(vo.getUserId() );
      out.write("</div>\r\n");
      out.write("								<div class=\"current_msg fl\">");
      out.print(messDao.getRecentChat(vo.getMsgListIdx()) );
      out.write("</div>\r\n");
      out.write("								<div style=\"display: none\" class=\"msgListIdx\">");
      out.print(vo.getMsgListIdx() );
      out.write("</div>\r\n");
      out.write("								<!--getRecentChat null값 확인하기-->				\r\n");
      out.write("							</a></div><!--chat_list-->\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"chatting_ fl\">\r\n");
      out.write("				<!-- <div class=\"chat_top\">\r\n");
      out.write("					<div>에어비앤비 고객지원 팀</div>\r\n");
      out.write("				</div>chat_top 	\r\n");
      out.write("				<div class=\"chat_center\">\r\n");
      out.write("					<div class=\"chat_center_middle\">\r\n");
      out.write("						<h3 class=\"chat_date\">2022.12.13</h3>\r\n");
      out.write("						<div class=\"chat_\">\r\n");
      out.write("							<div class=\"profile_pic fl\"><img aria-hidden=\"true\" decoding=\"async\" elementtiming=\"LCP-target\" src=\"https://a0.muscache.com/im/pictures/user/7e2794a8-3720-4469-b0d9-c134902ffd24.jpg?aki_policy=profile_x_medium\" data-original-uri=\"https://a0.muscache.com/im/pictures/user/7e2794a8-3720-4469-b0d9-c134902ffd24.jpg?aki_policy=profile_x_medium\" style=\"--dls-liteimage-object-fit: cover;\"></div>\r\n");
      out.write("							<div class=\"chat_content_outer fl\">\r\n");
      out.write("								<div class=\"chat_time_and_name\">\r\n");
      out.write("									<div class=\"name_ fl\">민영</div>\r\n");
      out.write("									<div class=\"time_ fl\">오후 4:49</div>\r\n");
      out.write("									<div class=\"see_more fr\"><svg viewBox=\"0 0 16 16\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 16px; width: 16px; fill: var(--fo-jk-r-s);\"><path d=\"m3 9.5c.82842712 0 1.5-.67157288 1.5-1.5s-.67157288-1.5-1.5-1.5-1.5.67157288-1.5 1.5.67157288 1.5 1.5 1.5zm5 0c.82842712 0 1.5-.67157288 1.5-1.5s-.67157288-1.5-1.5-1.5-1.5.67157288-1.5 1.5.67157288 1.5 1.5 1.5zm5 0c.8284271 0 1.5-.67157288 1.5-1.5s-.6715729-1.5-1.5-1.5-1.5.67157288-1.5 1.5.6715729 1.5 1.5 1.5z\"></path></svg></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"see_more_content\"><button class=\"delete_chat_button\">이 메시지 삭제하기</button></div>\r\n");
      out.write("								<div class=\"chat_content_inner\">아아 그럼일단 예약은 확정된거죠?? 계좌에는 따로 내역이 안찍혀서 걱정돼서요ㅠ</div>\r\n");
      out.write("							</div>chat_content_outer\r\n");
      out.write("						</div>chat_\r\n");
      out.write("					</div>\r\n");
      out.write("				</div> -->\r\n");
      out.write("			</div><!--chatting_-->\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("				<div class=\"chat_bottom\">\r\n");
      out.write("					<div class=\"chat_bottom_inner\">\r\n");
      out.write("						<div class=\"emoji_ fl\"><svg aria-label=\"ì´ëª¨í°ì½ ì í\" fill=\"currentColor\" height=\"24\" role=\"img\" viewBox=\"0 0 24 24\" width=\"24\"><title>ì´ëª¨í°ì½ ì í</title><path d=\"M15.83 10.997a1.167 1.167 0 1 0 1.167 1.167 1.167 1.167 0 0 0-1.167-1.167Zm-6.5 1.167a1.167 1.167 0 1 0-1.166 1.167 1.167 1.167 0 0 0 1.166-1.167Zm5.163 3.24a3.406 3.406 0 0 1-4.982.007 1 1 0 1 0-1.557 1.256 5.397 5.397 0 0 0 8.09 0 1 1 0 0 0-1.55-1.263ZM12 .503a11.5 11.5 0 1 0 11.5 11.5A11.513 11.513 0 0 0 12 .503Zm0 21a9.5 9.5 0 1 1 9.5-9.5 9.51 9.51 0 0 1-9.5 9.5Z\"></path></svg></div>\r\n");
      out.write("						<div id=\"emoji_list\">\r\n");
      out.write("							<div>\r\n");
      out.write("							");

								for(EmojiVo vo : listEmojiVo){
									if(vo.getEmoji_idx() % 6 == 1)
										out.println("<ul>");
									out.println("<li class=\"emoji\">" + vo.getEmoji_url() + "</li>");
									if(vo.getEmoji_idx() % 6 == 0)
										out.println("</ul>");
								}
							
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div><!--emoji_list-->\r\n");
      out.write("						<div class=\"input_content fl\">\r\n");
      out.write("								<input type=\"text\" value=\"\" placeholder=\"메시지를 입력하세요...\" class=\"input_content_inner\"/>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chat_etc fl\">\r\n");
      out.write("							<div class=\"fr\"><svg aria-label=\"ì¢ìì\" fill=\"currentColor\" height=\"24\" role=\"img\" viewBox=\"0 0 24 24\" width=\"24\"><title>ì¢ìì</title><path d=\"M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938m0-2a6.04 6.04 0 0 0-4.797 2.127 6.052 6.052 0 0 0-4.787-2.127A6.985 6.985 0 0 0 .5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 0 0 3.518 3.018 2 2 0 0 0 2.174 0 45.263 45.263 0 0 0 3.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 0 0-6.708-7.218Z\"></path></svg></div>\r\n");
      out.write("							<div class=\"fr\"><svg aria-label=\"ì¬ì§ ëë ëìì ì¶ê°\" fill=\"currentColor\" height=\"24\" role=\"img\" viewBox=\"0 0 24 24\" width=\"24\"><title>ì¬ì§ ëë ëìì ì¶ê°</title><path d=\"M6.549 5.013A1.557 1.557 0 1 0 8.106 6.57a1.557 1.557 0 0 0-1.557-1.557Z\" fill-rule=\"evenodd\"></path><path d=\"m2 18.605 3.901-3.9a.908.908 0 0 1 1.284 0l2.807 2.806a.908.908 0 0 0 1.283 0l5.534-5.534a.908.908 0 0 1 1.283 0l3.905 3.905\" fill=\"none\" stroke=\"currentColor\" stroke-linejoin=\"round\" stroke-width=\"2\"></path><path d=\"M18.44 2.004A3.56 3.56 0 0 1 22 5.564h0v12.873a3.56 3.56 0 0 1-3.56 3.56H5.568a3.56 3.56 0 0 1-3.56-3.56V5.563a3.56 3.56 0 0 1 3.56-3.56Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"></path></svg></div>\r\n");
      out.write("						</div><!--chat_ect-->\r\n");
      out.write("					</div><!--chat_bottom_inner-->\r\n");
      out.write("				</div><!--chat_bottom-->\r\n");
      out.write("		</div><!--content-->\r\n");
      out.write("	</body>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\".emoji\").click(function(){\r\n");
      out.write("			let str = $(\".input_content_inner\").val();\r\n");
      out.write("			let t = $(this).html();\r\n");
      out.write("			$(\".input_content_inner\").val(str + t);\r\n");
      out.write("		});\r\n");
      out.write("		$(\".chat_list\").click(function(){\r\n");
      out.write("			let command = \"showChat\";\r\n");
      out.write("			let msgListIdx = $(this).find(\".msgListIdx\").html();\r\n");
      out.write("			let userIdx = ");
      out.print(userIdx );
      out.write(";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : 'SesController',\r\n");
      out.write("				data : {\"command\" : command, \"msgListIdx\" : msgListIdx, \"userIdx\" : userIdx},\r\n");
      out.write("				type : 'post',\r\n");
      out.write("				success : function(arr){\r\n");
      out.write("					let str= \"<div class=\\\"chat_top\\\">\"\r\n");
      out.write("							+	\"<div>\"+arr[0].userId+\"<div/>\"	\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+\"<div class=\\\"chat_center\\\">\"\r\n");
      out.write("							+	\"<div class=\\\"chat_center_middle\\\">\";\r\n");
      out.write("					for(let i = 0; i < arr.length; i++){\r\n");
      out.write("						str +=   \"<div class=\\\"chat_\\\">\"\r\n");
      out.write("								+	\"<div class=\\\"profile_pic fl\\\"><img src=\\\"\"+ arr[i].userImage+ \"\\\"/></div>\"\r\n");
      out.write("								+	\"<div class=\\\"chat_content_outer fl\\\">\"\r\n");
      out.write("								+		\"<div class=\\\"chat_time_and_name\\\">\"\r\n");
      out.write("								+			\"<div class=\\\"name_ fl\\\">\" + arr[i].userId +\"</div>\"\r\n");
      out.write("								+			\"<div class=\\\"time_ fl\\\">\" + arr[i].dateTime + \"</div>\"\r\n");
      out.write("								+			\"<div class=\\\"see_more fr\\\"><svg viewBox=\\\"0 0 16 16\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" aria-hidden=\\\"true\\\" role=\\\"presentation\\\" focusable=\\\"false\\\" style=\\\"display: block; height: 16px; width: 16px; fill: var(--fo-jk-r-s);\\\"><path d=\\\"m3 9.5c.82842712 0 1.5-.67157288 1.5-1.5s-.67157288-1.5-1.5-1.5-1.5.67157288-1.5 1.5.67157288 1.5 1.5 1.5zm5 0c.82842712 0 1.5-.67157288 1.5-1.5s-.67157288-1.5-1.5-1.5-1.5.67157288-1.5 1.5.67157288 1.5 1.5 1.5zm5 0c.8284271 0 1.5-.67157288 1.5-1.5s-.6715729-1.5-1.5-1.5-1.5.67157288-1.5 1.5.6715729 1.5 1.5 1.5z\\\"></path></svg></div>\"\r\n");
      out.write("								+		\"</div>\"\r\n");
      out.write("								+		\"<div class=\\\"see_more_content\\\"><button class=\\\"delete_chat_button\\\">이 메시지 삭제하기</button></div>\"\r\n");
      out.write("								+		\"<div class=\\\"chat_content_inner\\\">\" + arr[i].msg + \"</div>\"\r\n");
      out.write("								+	\"</div>\"\r\n");
      out.write("								+\"</div>\"\r\n");
      out.write("					}\r\n");
      out.write("					str += \"</div></div> <div id=\\\"msg_list_idx\\\" style=\\\"display:none;\\\">\" + arr[0].msgListIdx + \"</div>\";\r\n");
      out.write("					$(\".chatting_\").html(str);\r\n");
      out.write("				},\r\n");
      out.write("				error : function(r, s, e){\r\n");
      out.write("					alert(\"[에러] code : \" + r.status\r\n");
      out.write("							+ \"message :\" + r.responseText\r\n");
      out.write("							+ \"error : \" + e);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		//채팅날리기\r\n");
      out.write("	 	/* let webSocket = \r\n");
      out.write("                 new WebSocket(\"ws://localhost:9090/Jsp1/broadcasting\");\r\n");
      out.write("      	webSocket.onmessage = function(e) {\r\n");
      out.write("         //채팅 추가하기\r\n");
      out.write("    		  //$(\"#div_message\").append(\"<p class='chat'>\"+e.data+\"</p>\");\r\n");
      out.write("      	}\r\n");
      out.write("      	webSocket.onopen = function(e) {\r\n");
      out.write("       	  alert(\"채팅에 참여하였습니다\");\r\n");
      out.write("      	}\r\n");
      out.write("      	webSocket.onerror = function(e) {\r\n");
      out.write("      	   alert(\"error!\");\r\n");
      out.write("      	}\r\n");
      out.write("		$(\".chat_etc > div:first-child \").click(function(){\r\n");
      out.write("			let msgListIdx = $(\"#msg_list_idx\").html();\r\n");
      out.write("		}); */\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
