/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-02-05 12:28:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import esDao.*;
import esVo.*;
import java.util.ArrayList;

public final class notification_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("esDao");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("esVo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	NotificationDao notiDao = new NotificationDao();
	UserInfoDao uiDao = new UserInfoDao();
	LanguageDao langDao = new LanguageDao();
	ArrayList<LanguageVo> listLanguageVo = langDao.getLanguage();
	LoginDao LoginDao = new LoginDao();
	int userIdx = 0;
	UserInfoVo userList = null;
	int howManyAlarm = 0;
	try{
		userIdx = (Integer)request.getSession().getAttribute("userIdx"); //--> 로그인창 만들면 이걸로 적용하기	
		userList = LoginDao.getUserInfoBy(userIdx);
		howManyAlarm = (Integer)LoginDao.getCountAlarm(userIdx);
	} catch (NullPointerException e){
		e.printStackTrace();
	}
	ArrayList<NotificationVo> listNotificationVo = notiDao.getAllList(userIdx);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset=\"UTF-8\">\r\n");
      out.write("      <title>알림</title>\r\n");
      out.write("      <link rel=\"shortcut icon\" href=\"images/logo2.png\">\r\n");
      out.write("      <link rel =\"stylesheet\" href=\"css/notification.css\"/>\r\n");
      out.write("      <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("      <script src=\"js/notification.js\"></script>\r\n");
      out.write("   </head>\r\n");
      out.write("   <!--<div style =\"clear : both;\"></div>-->\r\n");
      out.write("   <body id=\"body\">\r\n");
      out.write("      <div class=\"currency_language_background\"></div>\r\n");
      out.write("            <div id=\"currency_language_\">\r\n");
      out.write("               <button class=\"close_div\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;\"><path d=\"m6 6 20 20M26 6 6 26\"></path></svg></button>\r\n");
      out.write("               <div id=\"currency_\">\r\n");
      out.write("                  <div id=\"currency_top\">\r\n");
      out.write("                     <button class=\"currency_button fl\">언어와 지역</button>\r\n");
      out.write("                     <button class=\"language_button fl\">통화</button>\r\n");
      out.write("                  </div><!--currency_top-->\r\n");
      out.write("                  <div id=\"currency_center\">\r\n");
      out.write("                     <div>\r\n");
      out.write("                         <h2>추천 언어 및 지역</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"fl\">\r\n");
      out.write("                              <div>한국어</div>\r\n");
      out.write("                              <div>대한민국</div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li class=\"fl\">\r\n");
      out.write("                              <div>English</div>\r\n");
      out.write("                              <div>United States</div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div>\r\n");
      out.write("                        <h3 style=\"font-size: 22px; font-weight: 600;\">언어와 지역을 선택하세요</h3>\r\n");
      out.write("                         ");

                        	for( int i = 0; i <= 90; i++ ){
  								if(i % 5 == 0)
  									out.println("<ul>");
                        
      out.write("\r\n");
      out.write("                           <li class=\"fl\">\r\n");
      out.write("                              <div>");
      out.print(listLanguageVo.get(i).getLanguage() );
      out.write("</div>\r\n");
      out.write("                              <div>");
      out.print(listLanguageVo.get(i).getLocation() );
      out.write("</div>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        ");

                        	if(i % 5 == 4)
                        			out.println("</ul>");
                        	}
                        
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div><!--currency_center-->\r\n");
      out.write("               </div><!--currency_-->\r\n");
      out.write("               <div id=\"language_\"></div><!--language_-->\r\n");
      out.write("            </div><!--currency_language_-->\r\n");
      out.write("      <div id=\"header\">\r\n");
      out.write("         <div id=\"header_left\" class=\"fl\">\r\n");
      out.write("            <a href=\"Main2\"><img src=\"images/logo.png\" class=\"fr\"/></a>\r\n");
      out.write("         </div><!--header_left-- <!--airbnbë¡ê³ -->\r\n");
      out.write("         <div id=\"header_center\" class=\"fl\">\r\n");
      out.write("         </div><!--header_center--> \r\n");
      out.write("         <div id=\"header_right\" class=\"fl\">\r\n");
      out.write("            <div id=\"areaair\" class=\"fl\">\r\n");
      out.write("               <a href=\"doairbnb.jsp\"><strong>당신의 공간을 에어비앤비하세요</strong></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"globe\" class=\"fl\">\r\n");
      out.write("               <img src=\"images/globe.png\"/>\r\n");
      out.write("            </div><!--globe-->\r\n");
      out.write("            <div id=\"profile\" class=\"fl\">\r\n");
      out.write("              <img src=\"images/list.png\" style=\"margin: 21px 0 0 0px;\"/>\r\n");
      out.write("					");
 		if(userIdx == 0) { 
      out.write("\r\n");
      out.write("								<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 30px; width: 40px; fill: currentcolor; margin: -30px 0 0 41px;\"><path d=\"M16 .7C7.56.7.7 7.56.7 16S7.56 31.3 16 31.3 31.3 24.44 31.3 16 24.44.7 16 .7zm0 28c-4.02 0-7.6-1.88-9.93-4.81a12.43 12.43 0 0 1 6.45-4.4A6.5 6.5 0 0 1 9.5 14a6.5 6.5 0 0 1 13 0 6.51 6.51 0 0 1-3.02 5.5 12.42 12.42 0 0 1 6.45 4.4A12.67 12.67 0 0 1 16 28.7z\"></path></svg>\r\n");
      out.write("						");
  } else { 
      out.write("\r\n");
      out.write("								");
 if(userList.getUser_image() != null) { 
      out.write("\r\n");
      out.write("								<img src=\"");
      out.print(userList.getUser_image() );
      out.write("\"/>\r\n");
      out.write("								");
 } else { 
      out.write("\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 30px; width: 40px; fill: currentcolor; margin: -30px 0 0 41px;\"><path d=\"M16 .7C7.56.7.7 7.56.7 16S7.56 31.3 16 31.3 31.3 24.44 31.3 16 24.44.7 16 .7zm0 28c-4.02 0-7.6-1.88-9.93-4.81a12.43 12.43 0 0 1 6.45-4.4A6.5 6.5 0 0 1 9.5 14a6.5 6.5 0 0 1 13 0 6.51 6.51 0 0 1-3.02 5.5 12.42 12.42 0 0 1 6.45 4.4A12.67 12.67 0 0 1 16 28.7z\"></path></svg>\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("								");
 if ( howManyAlarm > 0) { 
      out.write("\r\n");
      out.write("								<div id=\"notice\">");
      out.print(howManyAlarm );
      out.write("</div>\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("						");
    } 
      out.write("\r\n");
      out.write("            </div><!--profile-->\r\n");
      out.write("            <div style =\"clear : both;\"></div>\r\n");
      out.write("            <div class=\"profile_list\">\r\n");
      out.write("            	");
 if(userIdx > 0) { 
      out.write(" \r\n");
      out.write("               <div class=\"profile_list_top\">\r\n");
      out.write("                  <form action=\"SesController\" method=\"post\">\r\n");
      out.write("					 <input type=\"submit\" value=\"메시지\"/>\r\n");
      out.write("					 <input type=\"hidden\" name=\"thisUserIdx\" value=\"0\"/>\r\n");
      out.write("					 <input type=\"hidden\" name=\"command\" value=\"message\"/>\r\n");
      out.write("				  </form>\r\n");
      out.write("                  <form action=\"notification.jsp\" method=\"post\">\r\n");
      out.write("                     <input type=\"submit\" value=\"알림\"/>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  <form action=\"trip.jsp\" method=\"post\">\r\n");
      out.write("                     <input type=\"submit\" value=\"여행\"/>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  <form action=\"wishlist.jsp\" method=\"post\">\r\n");
      out.write("                     <input type=\"submit\" value=\"위시리스트\"/>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div><!--profile_list_top-->\r\n");
      out.write("               <div class=\"profile_list_center\">\r\n");
      out.write("                  <form action=\"doairbnb.jsp\" method=\"post\">\r\n");
      out.write("                     <input type=\"submit\" value=\"당신의 공간을 에어비앤비하세요\"/>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  <form action=\"account.jsp\" method=\"post\">\r\n");
      out.write("                     <input type=\"submit\" value=\"계정\"/>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div><!--profile_list_center-->\r\n");
      out.write("               <div class=\"profile_list_bottom\">\r\n");
      out.write("                  <form action=\"timeline.jsp\" method=\"post\">\r\n");
      out.write("                     <input type=\"submit\" value=\"타임라인\"/>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  <div class=\"Logout\">로그아웃</div>\r\n");
      out.write("               </div><!--profile_list_bottom-->\r\n");
      out.write("               ");
 } else{ 
      out.write("\r\n");
      out.write("					<div class=\"profile_list_diff\">\r\n");
      out.write("						<div>로그인</div>\r\n");
      out.write("						<div>회원가입</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("            </div><!--profile_list-->\r\n");
      out.write("         </div><!--header_right-->\r\n");
      out.write("         <div style =\"clear : both;\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      	<!-- 회원가입창 -->\r\n");
      out.write("   <div id=\"joinmember_outer\"></div>\r\n");
      out.write("      <div id=\"joinmember\">\r\n");
      out.write("      \r\n");
      out.write("         <div class=\"jm_header\">\r\n");
      out.write("            <button>\r\n");
      out.write("               <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"\r\n");
      out.write("                  aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"\r\n");
      out.write("                  style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: 0 auto;\">\r\n");
      out.write("                  <path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("            <h2>로그인 또는 회원 가입</h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"jm_section\">\r\n");
      out.write("            <h2>에어비엔비에 오신것을 환영합니다</h2>\r\n");
      out.write("         \r\n");
      out.write("            <form id=\"jm_form\" action=\"Controller\" method=\"post\">\r\n");
      out.write("               <div>\r\n");
      out.write("                  <label for=\"jm_form\" id=\"code\"></label> \r\n");
      out.write("                  <select name=\"jm_code\" class=\"jm_seclect_box\">\r\n");
      out.write("                     <option value=\"korean\">선호하는 언어</option>\r\n");
      out.write("                     ");
 for(int i = 0; i <= 90; i++) { 
      out.write("\r\n");
      out.write("                  	 		<option>");
      out.print(listLanguageVo.get(i).getLocation() );
      out.write("</option>\r\n");
      out.write("                  	 ");
 } 
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("	               </div>\r\n");
      out.write("	               \r\n");
      out.write("	               <input type=\"text\" class=\"jm_phnum\" placeholder=\"전화번호\" name=\"phone_num\" required/>\r\n");
      out.write("	           	   <input type=\"password\" class=\"password\" placeholder=\"비밀번호\" name=\"pw\" required/>\r\n");
      out.write("	               <span>전화나 문자로 전화번호를 확인하겠습니다. 일반 문자 메시지 요금 및 데이터 요금이 부과됩니다.</span>\r\n");
      out.write("	         	   <input type=\"hidden\" name=\"url\" value=\"notification.jsp\"/>\r\n");
      out.write("	               <input type=\"submit\" class=\"jm_submit\" value=\"로그인\"><br/>\r\n");
      out.write("	               <input type=\"hidden\" name=\"command\" value=\"login\"/>\r\n");
      out.write("               <div class=\"join_user\" style=\"padding-top: 16px;\">회원 가입</div>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"join_user\">\r\n");
      out.write("      		<button>\r\n");
      out.write("               <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"\r\n");
      out.write("                  aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"\r\n");
      out.write("                  style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: 0 auto;\">\r\n");
      out.write("                  <path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("      		<form method=\"post\" class=\"join_user_form\" action=\"Controller\">\r\n");
      out.write("      			이름 : <input type=\"text\" placeholder=\"Ex) 김철수\" name=\"user_id\" required/> <br/><br/><br/>\r\n");
      out.write("      			비밀번호 : <input type=\"password\" name=\"pw\" required/> <br/><br/><br/>\r\n");
      out.write("      			비밀번호 확인 : <input type=\"password\" class=\"check_pw\" required/> <br/><br/><br/>\r\n");
      out.write("      			휴대폰 번호 : <input type=\"number\" name=\"phone_num\" placeholder=\"010xxxx1234\" required/> <br/><br/><br/>\r\n");
      out.write("      			거주지 : <input type=\"text\" name=\"user_regidence\" required/> <br/><br/><br/>\r\n");
      out.write("      			생년월일 : <input type=\"text\" name=\"birthday\" placeholder=\"2000/12/12\"required/> <br/><br/><br/>\r\n");
      out.write("      			이메일 : <input type=\"email\" name=\"email\" placeholder=\"asd123@naver.com\" required/> <br/><br/><br/><br/>\r\n");
      out.write("      			<input type=\"hidden\" name=\"command\" value=\"join\"/>\r\n");
      out.write("      			<input type=\"submit\" style=\"width: 500px; background-color: rgb(255,56,92); border-radius: 10px; color: white; border: none;}\"/>\r\n");
      out.write("      		</form>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--회원가입창 끝  -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("         <div>\r\n");
      out.write("            <div id=\"notice_block\">\r\n");
      out.write("               <div id=\"notice_title\">\r\n");
      out.write("                  <p>알림</p>\r\n");
      out.write("               </div><!--notice_title-->\r\n");
      out.write("               <div id=\"notice_total_div\">\r\n");
      out.write("               ");

               for(NotificationVo vo : listNotificationVo) {
    				UserInfoVo userVo = uiDao.getUserInfoByUserIdx(vo.getUser_idx());        	    
	       			String date = vo.getDate();
	    			String year = date.substring(0,4);
	    			String month = date.substring(5,7);
	    			
	    			String txt = vo.getTxt();
	    			// (((user_id))) 교체
	    			txt = txt.replace("(((user_id)))", userVo.getUser_id());
               
      out.write("\r\n");
      out.write("	               <!-- 반복 -->\r\n");
      out.write("	               ");
 if(userIdx > 0) {
      out.write("\r\n");
      out.write("	               <div class=\"notice_txt\">\r\n");
      out.write("	                  <div>\r\n");
      out.write("	                     <div>\r\n");
      out.write("	                        <a href=\"profile_timeline.jsp?thisUserIdx=");
      out.print(userIdx);
      out.write("\"><img src=\"");
      out.print(userVo.getUser_image());
      out.write("\"/></a>\r\n");
      out.write("	                     </div><!--notice_img-->\r\n");
      out.write("	                     <div>");
      out.print(txt );
      out.write("</div><!--notice_txt_inner-->\r\n");
      out.write("	                     <div>");
      out.print(year);
      out.write('년');
      out.write(' ');
      out.print(month);
      out.write("월</div><!--notice_date-->\r\n");
      out.write("	                     <div class=\"fr\">\r\n");
      out.write("	                        <button class=\"delete_button\" value=\"");
      out.print(vo.getNotification_idx() );
      out.write("\">\r\n");
      out.write("	                        <img src=\"images/delete.png\"/>\r\n");
      out.write("	                        </button>\r\n");
      out.write("	                     </div><!--delete button-->\r\n");
      out.write("	                  </div>\r\n");
      out.write("	               </div><!--notice_txt-->\r\n");
      out.write("	           ");

	               }
	           }
	           
      out.write("    \r\n");
      out.write("      				<script>\r\n");
      out.write("      					$(function(){\r\n");
      out.write("      						$(\".delete_button\").click(function(){\r\n");
      out.write("      							let idx = $(this).val();\r\n");
      out.write("      							let command = \"deleteNotification\"\r\n");
      out.write("								$.ajax({\r\n");
      out.write("									type : \"post\",\r\n");
      out.write("									url : \"Controller\",\r\n");
      out.write("									data : { \"idx\" : idx , \"command\" : command },\r\n");
      out.write("									success : function(){ },\r\n");
      out.write("									error : function(r, s, e){\r\n");
      out.write("										alert(\"[에러] code : \" + r.status\r\n");
      out.write("													+ \"message :\" + r.responseText\r\n");
      out.write("													+ \"error : \" + e);\r\n");
      out.write("									}\r\n");
      out.write("								});\r\n");
      out.write("      						});\r\n");
      out.write("      					});\r\n");
      out.write("      				</script>         \r\n");
      out.write("               </div><!--notice_total_div-->\r\n");
      out.write("            </div><!--notice_block-->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div><!--ë³¸ë¬¸content-->\r\n");
      out.write("      		<div id=\"footer\">\r\n");
      out.write("			<div id=\"footer_inner\">\r\n");
      out.write("				<div id=\"footer_list\">\r\n");
      out.write("					<section class=\"fl\">\r\n");
      out.write("						<h3>에어비앤비 지원</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>도움말 센터</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>안전 문제 관련 도움받기</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>에어커버</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>차별 반대</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>장애인 지원</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>예약 취소 옵션</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>이웃 민원 신고</li></a>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</section>\r\n");
      out.write("					<section class=\"fl\">\r\n");
      out.write("						<h3>호스팅</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>당신의 공간을 에어비앤비하세요</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>호스트를 위한 에어커버</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>호스팅 자료</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>커뮤니티 포럼</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>책임감 있는 호스팅</li></a>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</section>\r\n");
      out.write("					<section class=\"fl\">\r\n");
      out.write("						<h3>에어비앤비</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>뉴스룸</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>새로운 기능</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>채용정보</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>투자자 정보</li></a>\r\n");
      out.write("							<a href=\"OutOfService.jsp\"><li>Airbnb 긴급 숙소</li></a>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div><!--footer_list-->\r\n");
      out.write("				<div id=\"footer_under\">\r\n");
      out.write("					<div id=\"footer_under_top\">\r\n");
      out.write("						<div id=\"fut_left\">\r\n");
      out.write("							<div class=\"fl\">© 2023 Airbnb, Inc.</div>\r\n");
      out.write("							<span class=\"fl\">·</span>\r\n");
      out.write("							<a class=\"fl\">개인정보 처리방침</a>\r\n");
      out.write("							<span class=\"fl\">·</span>\r\n");
      out.write("							<a class=\"fl\" href=\"OutOfService.jsp\">이용약관</a>\r\n");
      out.write("							<span class=\"fl\">·</span>\r\n");
      out.write("							<a class=\"fl\" href=\"OutOfService.jsp\">사이트맵</a>\r\n");
      out.write("							<span class=\"fl\">·</span>\r\n");
      out.write("							<a class=\"fl\" href=\"OutOfService.jsp\">한국의 변경된 환불 정책</a>\r\n");
      out.write("							<span class=\"fl\">·</span>\r\n");
      out.write("							<a class=\"fl\" href=\"OutOfService.jsp\">회사 세부정보</a>\r\n");
      out.write("						</div><!--fut_left-->\r\n");
      out.write("						<div id=\"fut_right\" class=\"fr\">\r\n");
      out.write("							<div class=\"fl\">\r\n");
      out.write("								<button class=\"fl\">\r\n");
      out.write("									<svg class=\"fl\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 16px; width: 16px; fill: currentcolor;\"><path d=\"M8 .25a7.77 7.77 0 0 1 7.75 7.78 7.75 7.75 0 0 1-7.52 7.72h-.25A7.75 7.75 0 0 1 .25 8.24v-.25A7.75 7.75 0 0 1 8 .25zm1.95 8.5h-3.9c.15 2.9 1.17 5.34 1.88 5.5H8c.68 0 1.72-2.37 1.93-5.23zm4.26 0h-2.76c-.09 1.96-.53 3.78-1.18 5.08A6.26 6.26 0 0 0 14.17 9zm-9.67 0H1.8a6.26 6.26 0 0 0 3.94 5.08 12.59 12.59 0 0 1-1.16-4.7l-.03-.38zm1.2-6.58-.12.05a6.26 6.26 0 0 0-3.83 5.03h2.75c.09-1.83.48-3.54 1.06-4.81zm2.25-.42c-.7 0-1.78 2.51-1.94 5.5h3.9c-.15-2.9-1.18-5.34-1.89-5.5h-.07zm2.28.43.03.05a12.95 12.95 0 0 1 1.15 5.02h2.75a6.28 6.28 0 0 0-3.93-5.07z\"></path></svg>\r\n");
      out.write("									<a class=\"fl\" href=\"OutOfService.jsp\">한국어<strong>(KR)</strong></a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<span class=\"fl\">\r\n");
      out.write("									<span class=\"fl\" style=\"--footer-icon-spacing:5px; font-weight: 600;\"  class=\"i2is942 dir dir-ltr\">₩</span>\r\n");
      out.write("									<a href=\"OutOfService.jsp\">KRW</a>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ul class=\"fr\">\r\n");
      out.write("								<li class=\"fl\"><a href=\"OutOfService.jsp\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;height:18px;width:18px;fill:currentColor\" aria-label=\"íì´ì¤ë¶ì¼ë¡ ì´ëíê¸°\" role=\"img\" focusable=\"false\"><path d=\"M30 0a2 2 0 0 1 2 2v28a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2z\"></path><path fill=\"#fff\" d=\"M22.94 16H18.5v-3c0-1.27.62-2.5 2.6-2.5h2.02V6.56s-1.83-.31-3.58-.31c-3.65 0-6.04 2.21-6.04 6.22V16H9.44v4.62h4.06V32h5V20.62h3.73z\"></path></svg></a></li>\r\n");
      out.write("								<li class=\"fl\"><a href=\"OutOfService.jsp\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;height:18px;width:18px;fill:currentColor\" aria-label=\"í¸ìí°ë¡ ì´ëíê¸°\" role=\"img\" focusable=\"false\"><path d=\"M32 4v24a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4a4 4 0 0 1 4-4h24a4 4 0 0 1 4 4z\"></path><path fill=\"#fff\" d=\"M18.66 7.99a4.5 4.5 0 0 0-2.28 4.88A12.31 12.31 0 0 1 7.3 8.25a4.25 4.25 0 0 0 1.38 5.88c-.69 0-1.38-.13-2-.44a4.54 4.54 0 0 0 3.5 4.31 4.3 4.3 0 0 1-2 .06 4.64 4.64 0 0 0 4.19 3.13A8.33 8.33 0 0 1 5.8 23a12.44 12.44 0 0 0 19.32-11.19A7.72 7.72 0 0 0 27.3 9.5a8.3 8.3 0 0 1-2.5.75 4.7 4.7 0 0 0 2-2.5c-.87.5-1.81.87-2.81 1.06a4.5 4.5 0 0 0-5.34-.83z\"></path></svg></a></li>\r\n");
      out.write("								<li class=\"fl\"><a href=\"OutOfService.jsp\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;height:18px;width:18px;fill:currentColor\" aria-label=\"ì¸ì¤íê·¸ë¨ì¼ë¡ ì´ëíê¸°\" role=\"img\" focusable=\"false\"><path d=\"M30 0H2a2 2 0 0 0-2 2v28c0 1.1.9 2 2 2h28a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z\"></path><path fill=\"#fff\" d=\"M15.71 4h1.25c2.4 0 2.85.02 3.99.07 1.28.06 2.15.26 2.91.56.79.3 1.46.72 2.13 1.38.6.6 1.08 1.33 1.38 2.13l.02.06c.28.74.48 1.58.54 2.8l.01.4c.05 1.02.06 1.63.06 4.4v.92c0 2.6-.02 3.05-.07 4.23a8.78 8.78 0 0 1-.56 2.91c-.3.8-.77 1.53-1.38 2.13a5.88 5.88 0 0 1-2.13 1.38l-.06.02c-.74.28-1.59.48-2.8.53l-.4.02c-1.02.05-1.63.06-4.4.06h-.92a73.1 73.1 0 0 1-4.23-.07 8.78 8.78 0 0 1-2.91-.56c-.8-.3-1.53-.77-2.13-1.38a5.88 5.88 0 0 1-1.38-2.13l-.02-.06a8.84 8.84 0 0 1-.54-2.8l-.01-.37A84.75 84.75 0 0 1 4 16.29v-1c0-2.62.02-3.06.07-4.24.06-1.26.26-2.13.55-2.88l.01-.03c.3-.8.77-1.53 1.38-2.13a5.88 5.88 0 0 1 2.13-1.38l.06-.02a8.84 8.84 0 0 1 2.8-.54l.37-.01C12.39 4 12.99 4 15.71 4zm.91 2.16h-1.24c-2.3 0-2.91.01-3.81.05l-.42.02c-1.17.05-1.8.25-2.23.41-.56.22-.96.48-1.38.9-.4.41-.67.8-.88 1.35l-.03.06a6.7 6.7 0 0 0-.4 2.2l-.02.45c-.04.9-.05 1.53-.05 3.94v1.08c0 2.64.02 3.05.07 4.23v.07c.06 1.13.25 1.74.42 2.16.21.56.47.96.9 1.38.4.4.8.67 1.34.88l.06.03a6.7 6.7 0 0 0 2.2.4l.45.02c.9.04 1.53.05 3.94.05h1.08c2.64 0 3.05-.02 4.23-.07h.07a6.51 6.51 0 0 0 2.16-.42c.52-.19.99-.5 1.38-.9.4-.4.67-.8.88-1.34l.03-.06a6.7 6.7 0 0 0 .4-2.2l.02-.45c.04-.9.05-1.53.05-3.94v-1.09c0-2.63-.02-3.04-.07-4.22v-.07a6.51 6.51 0 0 0-.42-2.16c-.19-.52-.5-.99-.9-1.38a3.7 3.7 0 0 0-1.34-.88l-.06-.03a6.63 6.63 0 0 0-2.16-.4l-.46-.02c-.9-.04-1.5-.05-3.8-.05zM16 9.84a6.16 6.16 0 1 1 0 12.32 6.16 6.16 0 0 1 0-12.32zM16 12a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm6.4-3.85a1.44 1.44 0 1 1 0 2.88 1.44 1.44 0 0 1 0-2.88z\"></path></svg></a></li>\r\n");
      out.write("								<li class=\"fl\"><a href=\"OutOfService.jsp\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;height:18px;width:18px;fill:currentColor\" aria-label=\"ë¤ì´ë² ë¸ë¡ê·¸ë¡ ì´ëíê¸°\" role=\"img\" focusable=\"false\"><path fill=\"#222\" d=\"M30 0a2 2 0 0 1 2 2v28a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2z\"></path><path fill=\"#fff\" d=\"M23.92 6A4.1 4.1 0 0 1 28 9.88l.01.2v9.84A4.08 4.08 0 0 1 24.13 24h-5.86l-1.91 3.31a.45.45 0 0 1-.73.08l-.05-.08-1.91-3.3h-5.6a4.08 4.08 0 0 1-4.06-3.87l-.01-.2v-9.86a4.08 4.08 0 0 1 3.87-4.06l.2-.01zm-1.99 7.22c-1.13 0-2.05.95-2.05 2.12 0 1.16.92 2.1 2.05 2.1.47 0 .9-.15 1.24-.42v.59l-.03.08-.05.1c-.11.16-.36.39-.9.39v1.09h.22c.3-.02.87-.13 1.42-.61l.13-.13.05-.06.1-.12c.11-.17.26-.44.31-.76v-4.28h-1.25v.34a2.02 2.02 0 0 0-1.24-.43zM8.81 11.9H7.58v5.6H8.8v-.4c.35.3.79.5 1.27.5 1.1 0 2-.98 2-2.19s-.89-2.2-2-2.2c-.42 0-.81.15-1.14.4l-.13.1zm8.3 1.31c-1.23 0-2.23.98-2.23 2.2s1 2.18 2.23 2.18c1.22 0 2.22-.98 2.22-2.19s-1-2.19-2.22-2.19zm-3.35-.66a1.98 1.98 0 0 0-1.33-.75H12.22v1.12l.08.01c.14.04.44.16.56.5l.04.12v3.94h1.27v-3.97a2.12 2.12 0 0 0-.24-.7l-.08-.15zM9.84 14.3a1.1 1.1 0 1 1 0 2.19 1.1 1.1 0 0 1-1.12-1.1c0-.15.04-.3.1-.43.17-.4.56-.66 1.02-.66zm7.27.05c.58 0 1.06.47 1.06 1.04s-.47 1.05-1.06 1.05c-.6 0-1.07-.47-1.07-1.05s.48-1.04 1.07-1.04zm5.05-.11c.44 0 .83.24 1.01.6.08.15.12.3.12.48s-.05.34-.12.48c-.18.36-.57.6-1 .6a1.1 1.1 0 0 1-1.13-1.08c0-.6.5-1.08 1.12-1.08z\"></path></svg></a></li>\r\n");
      out.write("								<li class=\"fl\"><a href=\"OutOfService.jsp\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;height:18px;width:18px;fill:currentColor\" aria-label=\"ë¤ì´ë² í¬ì¤í¸ë¡ ì´ëíê¸°\" role=\"img\" focusable=\"false\"><path fill=\"#222\" d=\"M30 0a2 2 0 0 1 2 2v28a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2z\"></path><path fill=\"#fff\" d=\"M10 0h12.81v16.78l-5.88 10.13a.6.6 0 0 1-.99.09l-.06-.1L10 16.79z\"></path><path fill=\"#222\" d=\"M12.66 4.64v7.5h7.5v-7.5zm5.87 5.69h-1.5l-1.28-1.96v1.96h-1.47V6.45h1.43l1.32 1.95V6.45h1.5z\"></path></svg></a href=\"OutOfService.jsp\"></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div><!--fut_right-->\r\n");
      out.write("					</div><!--footer_under_top-->\r\n");
      out.write("					<div id=\"footer_under_bottom\">\r\n");
      out.write("웹사이트 제공자: Airbnb Ireland UC, private unlimited company, 8 Hanover Quay Dublin 2, D02 DP23 Ireland | 이사: Dermot Clarke, Killian Pattwell, Andrea Finnegan | VAT 번호: IE9827384L | 사업자 등록 번호: IE 511825 | 연락처: terms@airbnb.com, 웹사이트, 080-822-0230 | 호스팅 서비스 제공업체: 아마존 웹서비스 | 에어비앤비는 통신판매 중개자로 에어비앤비 플랫폼을 통하여 게스트와 호스트 사이에 이루어지는 통신판매의 당사자가 아닙니다. 에어비앤비 플랫폼을 통하여 예약된 숙소, 체험, 호스트 서비스에 관한 의무와 책임은 해당 서비스를 제공하는 호스트에게 있습니다.\r\n");
      out.write("					</div>\r\n");
      out.write("				</div><!--footer_under-->\r\n");
      out.write("			</div><!--footer_inner-->\r\n");
      out.write("		</div><!--ë°footer-->\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
